# Generated by Django 5.2 on 2025-05-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='follow_redirects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='timeout',
            field=models.IntegerField(default=30000),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
